export enum SceneName {
  Authentication = "Authentication",
  AddRecord="AddRecord",
  
  Chat = "Chat",
  EditProfile = "EditProfile",
  Home = "Home",
  Main = "Main",
  Meds = "Meds",
  Messages = "Messages",
  MyRecordsHome = "MyRecordsHome",
  MyTodoListHome = "MyTodoListHome",
  OneTimeCode = "OneTimeCode",
  Profile = "Profile",
  Reports = "Reports",
  Swipe = "Swipe",
  Symptoms = "Symptoms",
  Settings = "Settings",
  SocialHome = "SocialHome",
  TreatmentHome = "TreatmentHome",
  UserProfile = "UserProfile",
  // TopTabHome = "TopTabHome",
}
